In [4]:
import pandas as pd
import csv
from itertools import permutations

import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
import random as random


filePath  = "./AssetsValues/"

dataAssets = []
dataFramePerYear = []

firstYear = 2001
lastYear  = 2020

taxHavensList = {'AND': 'Andorra', 'AIA': 'Anguilla', 'ATG': 'Antigua and Barbuda', 'ABW':'Aruba', 'BHS': 'Bahamas', 'BHR':'Bahrain', 'BRB': 'Barbados', 'BLZ': 'Belize', 'BMU': 'Bermuda', 'VGB': 'Virgin Islands, British', 'CYM':'Cayman Islands', 'COK': 'Cook Islands',
				 'CRI': 'Costa Rica', 'CUW': 'Cura√ßao', 'CYP': 'Cyprus', 'DJI': 'Djibouti', 'DMA': 'Dominica', 'GIB': 'Gibraltar', 'GRD': 'Grenada', 'GGY': 'Guernsey', 'HKG': 'Hong Kong', 'IRL': 'Ireland', 'IMN': 'Isle of Man', 'JEY': 'Jersey', 'JOR': 'Jordan', 
				 'LBN': 'Lebanon', 'LBR': 'Liberia', 'LIE': 'Liechtenstein', 'LUX': 'Luxembourg', 'MAC': 'Macao', 'MDV': 'Maldives', 'MLT': 'Malta', 'MHL': 'Marshall Islands', 'MUS': 'Mauritius', 'FSM': 'Micronesia', 'MCO': 'Monaco', 'MSR': 'Montserrat', 'NRU': 'Nauru',
				 'ANT': 'Netherlands Antilles', 'NIU': 'Niue', 'PAN': 'Panama', 'WSM':'Samoa', 'SMR': 'San Marino', 'SYC': 'Seychelles', 'SGP': 'Singapore', 'KNA': 'St. Kitts and Nevis', 'LCA': 'St. Lucia', 'MAF':'St. Martin', 'VCT': 'St. Vincent and the Grenadines',
				 'CHE': 'Switzerland', 'TWN': 'Taiwan', 'TON': 'Tonga', 'TCA': 'Turks and Caicos', 'VUT': 'Vanuatu'}

In [6]:
def importCSVfiles():
    
    ##########################################
    ##
    ## Importing Assets DataFrame
    ##
    ##########################################
    for i in range(firstYear, lastYear+1):
        dataFrame = pd.read_csv(filePath+"Assets"+str(i)+".csv", encoding='ISO-8859-1')
        dataFrame.columns.values[0] = "Country" #[0] es el primer termino del dataframe
    
        dataFrame.fillna(0, inplace=True)                  ### QUITAR NANs
        dataFrame.replace(['-'], 0, inplace=True)          
        dataFrame.replace(['C'], 0, inplace=True)          ### "C" means that data are confidential. ## https://datahelp.imf.org/knowledgebase/articles/484340-what-does-the-symbol-c-mean-in-the-coordinated-d
    
        dataFrame.loc[:, dataFrame.columns != 'Country'] = dataFrame.loc[:, dataFrame.columns != 'Country'].applymap(lambda x: float(x.split()[0].replace(',', '')) if(hasattr(x, 'split')) else x)
    
        dataAssets.append(dataFrame)

In [8]:
importCSVfiles()
dataAssets[8]

,Country,ARG,ABW,AUS,AUT,BHS,BHR,BRB,BEL,BMU,...,ESP,SWE,CHE,THA,TUR,UKR,GBR,USA,URY,VEN
0,AFG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,ALB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0
2,DZA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,115.0,0.0,0.0,0.0
3,ASM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,AND,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,105.0,201.0,0.0,0.0,0.0,-60.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,PSE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234,ESH,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
235,YEM,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0
236,ZMB,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,...,0.0,2.0,0.0,0.0,0.0,0.0,150.0,51.0,0.0,0.0
237,ZWE,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,5.0,0.0,0.0,0.0,8.0,68.0,0.0,0.0

In [14]:
importCSVfiles()

for localYear in range(firstYear, lastYear+1):
	year = localYear

	countryList = list(dataAssets[year-firstYear].columns) #dataAssets[year-firstYear] te coge los datos del a√±o q tu quieres (2005-2001=4 --> cuarto elemento de dataAssets)
                                                            #te devuelve el nombre de cada columna, por eso el 1er termino es country
	countryList = countryList[1:len(countryList)] #paises de la fila (no columna) de dataAssets !!
	df = pd.DataFrame()

	#concatenating in one df per year
	for item in countryList: #para cada item de la lista
		countryOwner = item 
		df1 = pd.DataFrame()
		##########################################
		##
		## Each df1 is a Data Frame with the following columns
		## - column 1 (Target): Country that report asset over country of column 2
		## - column 2 (Source): Country that has to pay asset over country of column 1
		## - column 3 (Assets): Value of the Assets
		##
		## The graph would be something like:
		## country of column 1  <----(Asset)---- country of column 2...
		##
		##########################################

		df1['Source'] = dataAssets[year-firstYear]['Country'] #columna del dataAsset
		df1['Assets'] = dataAssets[year-firstYear][countryOwner] # countryowner=item. columna de assets que tiene el pais countryowner(longitud 237)
		df1.fillna(0.0, inplace=True)

		df1.insert(0, 'Target', countryOwner) #a√±adir una columna al inicio del dataFrame df1
		df1 = df1[df1.Assets > 0] #asegurarse de que los valores son positivos¬ø
		df1.reset_index(drop=True, inplace=True) #restablecer indices

		df = pd.concat([df,df1], ignore_index=True) #concatenar los dataframes

	dataFramePerYear.append(df)

In [15]:
def takeAsset(c1, c2, year):
	if year < firstYear or year > lastYear:
		print("Year should be between (and included) "+str(firstYear)+" and "+str(lastYear))
		return
	
	df = dataFramePerYear[year-firstYear]
	dfaux = df[df['Target'] == c1].copy()
	dfauxaux = dfaux[dfaux['Source'] == c2].copy()

	if dfauxaux.empty:
		print("Theres no Asset value between "+str(c1)+" and "+str(c2)+" in "+str(year)+".")
	else:
		print(dfauxaux.head(1))

# takeAsset('target','source')

In [16]:
takeAsset('BRA','PRT' , 2017)

    Target Source Assets
711    BRA    PRT  298.0

In [12]:
allyearsasset = []

# this cell displays all the assets exchanges for each year in a dataframe with three columns: target, source and asset value.
# it was performed because the dataframe dataAssets was too big

for i in range(0,19): 
    df = dataAssets[i]
    shape = df.shape
    (r,c) = shape
    sourcecount = df[['Country']] #paises source    
    sourcecountlist = sourcecount.to_numpy() #paises en array, lista
    targetcountlist = df.columns.values[1:c]
    #targetlistfin = targetcount.tolist() # df --> list
    dict1 = {}
    dict2 = {}
        
    targetdata = np.array([]) #array vacio para almacenar los paises
    countlist = np.array([]) #array vacio para almacenar los paises
    assetlist = np.array([])
            
    for target in targetcountlist: #para cada componente del array
            
        result1 = df[target]
        result = np.array(result1)  #df --> array
        result = (result != 0)
        res = list(filter(lambda i: result[i], range(len(result)))) #array de indices en los que pone true(diferente de 0)
                
        for i in res:
            scount = sourcecountlist[i]
            asset = result1[i]
            asset1 = int(asset)
            countlist = np.append(countlist,scount)     
            assetlist = np.append(assetlist,asset1)
                
        length = len(res)
        targetlist = [target]
        targetlist = targetlist * length
        targetdata = np.append(targetdata,targetlist)
                    
        dict1[target] = countlist
        dict2[target] = assetlist
        
    targetdata = targetdata.tolist() 
        
    d = {'target': targetdata, 'source': countlist, 'asset value': assetlist}
    Assetdata = pd.DataFrame(data=d)
    allyearsasset.append(Assetdata)

In [80]:
#print(allyearsasset[1].to_string())     # para imprimir toda la tabla

In [78]:
# it generates a different file .csv with the necessary assets data for each year.

for year in range(2001,2020):
    allyearsasset[year-2001].to_csv('allyearsasset' + str(year) + '.csv')